name: Report a Bug
description: Report a bug here on our issue tracker.
body:
- type: "input"
  attributes:
    label: "Labels"
    description: "To automatically label this issue, add the uppercase'd label(s) sourrounded by brackets"
    value: "[BUG]"
    placeholder: "[LABEL]"
