name: Report a Bug
description: Report a bug here on our issue tracker.
body:
- type: "input"
  id: "labels"
  attributes:
    label: "Labels"
    description: "To automatically label this issue, add the uppercase'd label(s) sourrounded by brackets"
    value: "[BUG]"
    placeholder: "[LABEL]"

- type: "input"
  id: "description"
  attributes:
    label: "Description"
    description: "Give a short and concise description of the bug"
    placeholder: "Explosive bees do not explode after being fed."
  validations:
    required: true

- type: "textarea"
  id: "steps"
  attributes:
    label: "Steps to reproduce"
    description: "Give a list of steps to recreate this issue"
 
